export const listOfStudents = [
  // Sửa từ "public/image/picture.jpg" thành "image/picture.jpg"
  { id: 1,
     name: "Cao Van Duy Son",
      avatar: "images/1.jpg",
       age: 21, grade: "10A1" },
  { id: 2,
     name: "Nguyen Van A",
      avatar: "images/2.jpg",
       age: 20, grade: "10A2" },
  { id: 3,
     name: "Tran Thi B",
      avatar: "images/3.jpg",
       age: 22, grade: "10A3" },
  { id: 4,
     name: "Le Van C",
      avatar: "images/4.jpg",
       age: 21, grade: "10A1" },
  { id: 5,
     name: "Pham Thi D",
      avatar: "images/5.jpg",
       age: 20, grade: "10B1" },
  { id: 6,
     name: "Hoang Van E",
      avatar: "images/6.jpg",
       age: 23, grade: "10C2" },
  { id: 7,
     name: "Vu Thi F",
      avatar: "images/7.jpg",
       age: 21, grade: "10A1" },
  { id: 8,
     name: "Dang Van G",
      avatar: "images/8.jpg",
       age: 22, grade: "10D1" },
  { id: 9,
     name: "Bui Thi H",
      avatar: "images/9.jpg",
       age: 20, grade: "10A2" },
  { id: 10,
     name: "Do Van I",
      avatar: "images/1.jpg",
       age: 21, grade: "10B2" },
];